
import java.util.HashMap;
import java.util.Map;
import org.clothoapi.clotho3javaapi.Clotho;
import org.clothoapi.clotho3javaapi.ClothoConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alexandra
 */
public class ClothoJavaGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClothoJavaGUI
     */
    public static final String clothoRemoteAddress = "wss://www.clothocad.org/websocket";
    public static final String clothoLocalAddress = "wss://localhost:8443/websocket";
    public ClothoConnection conn;
    public Clotho clothoObject;
    public static String username;
    public static String password;
    
    public ClothoJavaGUI() {
        initComponents();
        System.out.println("Testing Clotho");
        conn = new ClothoConnection(clothoLocalAddress);
        clothoObject = new Clotho(conn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPane = new javax.swing.JLayeredPane();
        NonaIcon = new javax.swing.JLabel();
        NyxIcon = new javax.swing.JLabel();
        BodyPane = new javax.swing.JPanel();
        MenuPane = new javax.swing.JTabbedPane();
        AboutPane = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StartText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        NyxText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        AboutText = new javax.swing.JTextArea();
        AccountPane = new javax.swing.JPanel();
        UserInput1 = new javax.swing.JTextField();
        LoginLabel = new javax.swing.JLabel();
        CreateUserLabel = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        CreateUserButton = new javax.swing.JButton();
        UserLabel2 = new javax.swing.JLabel();
        PassLabel1 = new javax.swing.JLabel();
        UserInput2 = new javax.swing.JTextField();
        PassLabel2 = new javax.swing.JLabel();
        UserLabel1 = new javax.swing.JLabel();
        PassInput1 = new javax.swing.JPasswordField();
        PassInput2 = new javax.swing.JPasswordField();
        FunctionsPane = new javax.swing.JPanel();
        FunctionsList = new javax.swing.JTabbedPane();
        CreatePane = new javax.swing.JPanel();
        JSONObjLabel = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        CreateHelp = new javax.swing.JButton();
        QueryPane = new javax.swing.JPanel();
        JSONObjLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        InsertJSONObj1 = new javax.swing.JTextArea();
        QueryButton = new javax.swing.JButton();
        QueryHelp = new javax.swing.JButton();
        GetPane = new javax.swing.JPanel();
        JSONObjLabel2 = new javax.swing.JLabel();
        IDInputGet = new javax.swing.JTextField();
        GetButton = new javax.swing.JButton();
        GetHelp = new javax.swing.JButton();
        DestroyPane = new javax.swing.JPanel();
        JSONObjLabel3 = new javax.swing.JLabel();
        IDInputDes = new javax.swing.JTextField();
        DestroyButton = new javax.swing.JButton();
        DestroyHelp = new javax.swing.JButton();
        SetPane = new javax.swing.JPanel();
        SetQLabel = new javax.swing.JLabel();
        SetELabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        SetEInput = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        SetQInput = new javax.swing.JTextArea();
        SetButton = new javax.swing.JButton();
        SetHelp = new javax.swing.JButton();
        DownloadsPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(48, 63, 159));
        setFocusable(false);
        setForeground(java.awt.Color.white);

        HeaderPane.setBackground(new java.awt.Color(48, 63, 159));
        HeaderPane.setOpaque(true);
        HeaderPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NonaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_11rsz_nonafoundation.png"))); // NOI18N
        HeaderPane.add(NonaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        NyxIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/L.png"))); // NOI18N
        HeaderPane.add(NyxIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        BodyPane.setBackground(new java.awt.Color(48, 63, 159));

        MenuPane.setBackground(new java.awt.Color(63, 81, 195));
        MenuPane.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N

        AboutPane.setBackground(new java.awt.Color(63, 81, 195));
        AboutPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 81, 195)));

        WelcomeLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 70)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(240, 240, 240));
        WelcomeLabel.setText("Welcome!");

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        StartText.setEditable(false);
        StartText.setBackground(new java.awt.Color(63, 81, 195));
        StartText.setColumns(20);
        StartText.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        StartText.setForeground(new java.awt.Color(255, 255, 255));
        StartText.setLineWrap(true);
        StartText.setRows(4);
        StartText.setText("Where to start: If you are completely new to Clotho, we \nrecommend starting with the general use tutorial. If you \nwould like to continue and develop your own application \nfor Clotho, the developer tutorial will show you the basics.");
        jScrollPane1.setViewportView(StartText);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        NyxText.setEditable(false);
        NyxText.setBackground(new java.awt.Color(63, 81, 195));
        NyxText.setColumns(20);
        NyxText.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        NyxText.setForeground(new java.awt.Color(255, 255, 255));
        NyxText.setLineWrap(true);
        NyxText.setRows(4);
        NyxText.setText("Nyx: She is the Greek goddess of the night and one of the \nprimordial gods responsible for the beginning of creation. \nIn some texts, she is the mother of the fates: Clotho, \nLachesis, and Atropos.");
        NyxText.setWrapStyleWord(true);
        jScrollPane2.setViewportView(NyxText);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        AboutText.setEditable(false);
        AboutText.setBackground(new java.awt.Color(63, 81, 195));
        AboutText.setColumns(20);
        AboutText.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        AboutText.setForeground(new java.awt.Color(255, 255, 255));
        AboutText.setLineWrap(true);
        AboutText.setRows(3);
        AboutText.setText("About: Nyx is a teaching application written in Java that \nworks with Clotho 3.0 through interacting with the Clotho \nJava API to demonstrate Clotho's abilities.");
        jScrollPane3.setViewportView(AboutText);

        javax.swing.GroupLayout AboutPaneLayout = new javax.swing.GroupLayout(AboutPane);
        AboutPane.setLayout(AboutPaneLayout);
        AboutPaneLayout.setHorizontalGroup(
            AboutPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPaneLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(AboutPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(0, 84, Short.MAX_VALUE))
            .addGroup(AboutPaneLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(WelcomeLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AboutPaneLayout.setVerticalGroup(
            AboutPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPaneLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(WelcomeLabel)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        MenuPane.addTab("About", AboutPane);

        AccountPane.setBackground(new java.awt.Color(63, 81, 195));

        UserInput1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        UserInput1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UserInput1.setMinimumSize(new java.awt.Dimension(6, 34));
        UserInput1.setPreferredSize(new java.awt.Dimension(130, 25));

        LoginLabel.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 36)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(197, 202, 233));
        LoginLabel.setText("Login:");

        CreateUserLabel.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 36)); // NOI18N
        CreateUserLabel.setForeground(new java.awt.Color(197, 202, 233));
        CreateUserLabel.setText("Create User:");

        LoginButton.setBackground(new java.awt.Color(83, 109, 254));
        LoginButton.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Enter");
        LoginButton.setContentAreaFilled(false);
        LoginButton.setOpaque(true);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        CreateUserButton.setBackground(new java.awt.Color(83, 109, 254));
        CreateUserButton.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        CreateUserButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateUserButton.setText("Enter");
        CreateUserButton.setContentAreaFilled(false);
        CreateUserButton.setOpaque(true);
        CreateUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateUserButtonActionPerformed(evt);
            }
        });

        UserLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        UserLabel2.setForeground(new java.awt.Color(197, 202, 233));
        UserLabel2.setText("Username:");

        PassLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        PassLabel1.setForeground(new java.awt.Color(197, 202, 233));
        PassLabel1.setText("Password:");

        UserInput2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        UserInput2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UserInput2.setPreferredSize(new java.awt.Dimension(130, 31));

        PassLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        PassLabel2.setForeground(new java.awt.Color(197, 202, 233));
        PassLabel2.setText("Password:");

        UserLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        UserLabel1.setForeground(new java.awt.Color(197, 202, 233));
        UserLabel1.setText("Username:");

        PassInput1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        PassInput1.setPreferredSize(new java.awt.Dimension(130, 25));

        PassInput2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        PassInput2.setPreferredSize(new java.awt.Dimension(130, 25));

        javax.swing.GroupLayout AccountPaneLayout = new javax.swing.GroupLayout(AccountPane);
        AccountPane.setLayout(AccountPaneLayout);
        AccountPaneLayout.setHorizontalGroup(
            AccountPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPaneLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(AccountPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateUserLabel)
                    .addComponent(LoginButton)
                    .addComponent(CreateUserButton)
                    .addComponent(LoginLabel)
                    .addGroup(AccountPaneLayout.createSequentialGroup()
                        .addGroup(AccountPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AccountPaneLayout.createSequentialGroup()
                                .addComponent(UserLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(UserInput2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(AccountPaneLayout.createSequentialGroup()
                                .addComponent(UserLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(UserInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(AccountPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AccountPaneLayout.createSequentialGroup()
                                .addComponent(PassLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(PassInput2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(AccountPaneLayout.createSequentialGroup()
                                .addComponent(PassLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(PassInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        AccountPaneLayout.setVerticalGroup(
            AccountPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPaneLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(LoginLabel)
                .addGap(18, 18, 18)
                .addGroup(AccountPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserLabel1)
                    .addComponent(UserInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassLabel1)
                    .addComponent(PassInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LoginButton)
                .addGap(54, 54, 54)
                .addComponent(CreateUserLabel)
                .addGap(18, 18, 18)
                .addGroup(AccountPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserLabel2)
                    .addComponent(UserInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassLabel2)
                    .addComponent(PassInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CreateUserButton)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        MenuPane.addTab("Account", AccountPane);

        FunctionsPane.setBackground(new java.awt.Color(63, 81, 181));

        FunctionsList.setBackground(new java.awt.Color(255, 255, 255));
        FunctionsList.setForeground(new java.awt.Color(48, 63, 159));
        FunctionsList.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        FunctionsList.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N

        CreatePane.setBackground(new java.awt.Color(63, 81, 195));

        JSONObjLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        JSONObjLabel.setForeground(new java.awt.Color(197, 202, 233));
        JSONObjLabel.setText("Insert Json Object:");

        CreateButton.setBackground(new java.awt.Color(83, 109, 254));
        CreateButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        CreateButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateButton.setText("Create");
        CreateButton.setContentAreaFilled(false);
        CreateButton.setOpaque(true);
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        CreateHelp.setBackground(new java.awt.Color(83, 109, 254));
        CreateHelp.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        CreateHelp.setForeground(new java.awt.Color(255, 255, 255));
        CreateHelp.setText("Help");
        CreateHelp.setContentAreaFilled(false);
        CreateHelp.setOpaque(true);

        javax.swing.GroupLayout CreatePaneLayout = new javax.swing.GroupLayout(CreatePane);
        CreatePane.setLayout(CreatePaneLayout);
        CreatePaneLayout.setHorizontalGroup(
            CreatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePaneLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(CreatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreatePaneLayout.createSequentialGroup()
                        .addComponent(CreateButton)
                        .addGap(18, 18, 18)
                        .addComponent(CreateHelp))
                    .addComponent(JSONObjLabel))
                .addContainerGap(486, Short.MAX_VALUE))
        );
        CreatePaneLayout.setVerticalGroup(
            CreatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePaneLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(JSONObjLabel)
                .addGap(362, 362, 362)
                .addGroup(CreatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateButton)
                    .addComponent(CreateHelp))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        FunctionsList.addTab("create", CreatePane);

        QueryPane.setBackground(new java.awt.Color(63, 81, 195));

        JSONObjLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        JSONObjLabel1.setForeground(new java.awt.Color(197, 202, 233));
        JSONObjLabel1.setText("Insert Json Object:");

        InsertJSONObj1.setColumns(20);
        InsertJSONObj1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        InsertJSONObj1.setRows(5);
        InsertJSONObj1.setText("{\n}");
        jScrollPane5.setViewportView(InsertJSONObj1);

        QueryButton.setBackground(new java.awt.Color(83, 109, 254));
        QueryButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        QueryButton.setForeground(new java.awt.Color(255, 255, 255));
        QueryButton.setText("Query");
        QueryButton.setContentAreaFilled(false);
        QueryButton.setOpaque(true);

        QueryHelp.setBackground(new java.awt.Color(83, 109, 254));
        QueryHelp.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        QueryHelp.setForeground(new java.awt.Color(255, 255, 255));
        QueryHelp.setText("Help");
        QueryHelp.setContentAreaFilled(false);
        QueryHelp.setOpaque(true);

        javax.swing.GroupLayout QueryPaneLayout = new javax.swing.GroupLayout(QueryPane);
        QueryPane.setLayout(QueryPaneLayout);
        QueryPaneLayout.setHorizontalGroup(
            QueryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QueryPaneLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(QueryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSONObjLabel1)
                    .addGroup(QueryPaneLayout.createSequentialGroup()
                        .addComponent(QueryButton)
                        .addGap(18, 18, 18)
                        .addComponent(QueryHelp)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        QueryPaneLayout.setVerticalGroup(
            QueryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QueryPaneLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(JSONObjLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(QueryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QueryButton)
                    .addComponent(QueryHelp))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        FunctionsList.addTab("query", QueryPane);

        GetPane.setBackground(new java.awt.Color(63, 81, 195));

        JSONObjLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        JSONObjLabel2.setForeground(new java.awt.Color(197, 202, 233));
        JSONObjLabel2.setText("Insert ID Number of Object to Get:");

        IDInputGet.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N

        GetButton.setBackground(new java.awt.Color(83, 109, 254));
        GetButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        GetButton.setForeground(new java.awt.Color(255, 255, 255));
        GetButton.setText("Get");
        GetButton.setContentAreaFilled(false);
        GetButton.setOpaque(true);

        GetHelp.setBackground(new java.awt.Color(83, 109, 254));
        GetHelp.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        GetHelp.setForeground(new java.awt.Color(255, 255, 255));
        GetHelp.setText("Help");
        GetHelp.setContentAreaFilled(false);
        GetHelp.setOpaque(true);

        javax.swing.GroupLayout GetPaneLayout = new javax.swing.GroupLayout(GetPane);
        GetPane.setLayout(GetPaneLayout);
        GetPaneLayout.setHorizontalGroup(
            GetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GetPaneLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addGroup(GetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GetPaneLayout.createSequentialGroup()
                        .addComponent(GetButton)
                        .addGap(18, 18, 18)
                        .addComponent(GetHelp))
                    .addGroup(GetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(IDInputGet, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JSONObjLabel2)))
                .addGap(212, 212, 212))
        );
        GetPaneLayout.setVerticalGroup(
            GetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GetPaneLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(JSONObjLabel2)
                .addGap(18, 18, 18)
                .addComponent(IDInputGet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(GetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetButton)
                    .addComponent(GetHelp))
                .addContainerGap(370, Short.MAX_VALUE))
        );

        FunctionsList.addTab("get", GetPane);

        DestroyPane.setBackground(new java.awt.Color(63, 81, 195));

        JSONObjLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        JSONObjLabel3.setForeground(new java.awt.Color(197, 202, 233));
        JSONObjLabel3.setText("Insert ID Number of Object to Destroy:");

        IDInputDes.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N

        DestroyButton.setBackground(new java.awt.Color(83, 109, 254));
        DestroyButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        DestroyButton.setForeground(new java.awt.Color(255, 255, 255));
        DestroyButton.setText("Destroy");
        DestroyButton.setContentAreaFilled(false);
        DestroyButton.setOpaque(true);

        DestroyHelp.setBackground(new java.awt.Color(83, 109, 254));
        DestroyHelp.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        DestroyHelp.setForeground(new java.awt.Color(255, 255, 255));
        DestroyHelp.setText("Help");
        DestroyHelp.setContentAreaFilled(false);
        DestroyHelp.setOpaque(true);

        javax.swing.GroupLayout DestroyPaneLayout = new javax.swing.GroupLayout(DestroyPane);
        DestroyPane.setLayout(DestroyPaneLayout);
        DestroyPaneLayout.setHorizontalGroup(
            DestroyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DestroyPaneLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(DestroyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DestroyPaneLayout.createSequentialGroup()
                        .addComponent(DestroyButton)
                        .addGap(18, 18, 18)
                        .addComponent(DestroyHelp))
                    .addGroup(DestroyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JSONObjLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IDInputDes)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        DestroyPaneLayout.setVerticalGroup(
            DestroyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DestroyPaneLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(JSONObjLabel3)
                .addGap(18, 18, 18)
                .addComponent(IDInputDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DestroyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DestroyButton)
                    .addComponent(DestroyHelp))
                .addContainerGap(370, Short.MAX_VALUE))
        );

        FunctionsList.addTab("destroy", DestroyPane);

        SetPane.setBackground(new java.awt.Color(63, 81, 195));

        SetQLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        SetQLabel.setForeground(new java.awt.Color(240, 240, 240));
        SetQLabel.setText("Query the Object you wish to edit here:");

        SetELabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        SetELabel.setForeground(new java.awt.Color(240, 240, 240));
        SetELabel.setText("Edit the Object here:");

        SetEInput.setColumns(20);
        SetEInput.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        SetEInput.setRows(5);
        jScrollPane6.setViewportView(SetEInput);

        SetQInput.setColumns(20);
        SetQInput.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        SetQInput.setRows(5);
        SetQInput.setText("{\n}");
        jScrollPane7.setViewportView(SetQInput);

        SetButton.setBackground(new java.awt.Color(83, 109, 254));
        SetButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        SetButton.setForeground(new java.awt.Color(255, 255, 255));
        SetButton.setText("Enter Changes");
        SetButton.setContentAreaFilled(false);
        SetButton.setOpaque(true);
        SetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetButtonActionPerformed(evt);
            }
        });

        SetHelp.setBackground(new java.awt.Color(83, 109, 254));
        SetHelp.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        SetHelp.setForeground(new java.awt.Color(255, 255, 255));
        SetHelp.setText("Help");
        SetHelp.setContentAreaFilled(false);
        SetHelp.setOpaque(true);

        javax.swing.GroupLayout SetPaneLayout = new javax.swing.GroupLayout(SetPane);
        SetPane.setLayout(SetPaneLayout);
        SetPaneLayout.setHorizontalGroup(
            SetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SetPaneLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(SetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(SetPaneLayout.createSequentialGroup()
                        .addComponent(SetButton)
                        .addGap(18, 18, 18)
                        .addComponent(SetHelp))
                    .addComponent(SetELabel)
                    .addComponent(SetQLabel))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        SetPaneLayout.setVerticalGroup(
            SetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SetPaneLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(SetQLabel)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SetELabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(SetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetButton)
                    .addComponent(SetHelp))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        FunctionsList.addTab("set", SetPane);

        javax.swing.GroupLayout FunctionsPaneLayout = new javax.swing.GroupLayout(FunctionsPane);
        FunctionsPane.setLayout(FunctionsPaneLayout);
        FunctionsPaneLayout.setHorizontalGroup(
            FunctionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FunctionsList, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        FunctionsPaneLayout.setVerticalGroup(
            FunctionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FunctionsPaneLayout.createSequentialGroup()
                .addComponent(FunctionsList, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 246, Short.MAX_VALUE))
        );

        MenuPane.addTab("Functions", FunctionsPane);

        DownloadsPane.setBackground(new java.awt.Color(63, 81, 195));

        javax.swing.GroupLayout DownloadsPaneLayout = new javax.swing.GroupLayout(DownloadsPane);
        DownloadsPane.setLayout(DownloadsPaneLayout);
        DownloadsPaneLayout.setHorizontalGroup(
            DownloadsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );
        DownloadsPaneLayout.setVerticalGroup(
            DownloadsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
        );

        MenuPane.addTab("Resources", DownloadsPane);

        javax.swing.GroupLayout BodyPaneLayout = new javax.swing.GroupLayout(BodyPane);
        BodyPane.setLayout(BodyPaneLayout);
        BodyPaneLayout.setHorizontalGroup(
            BodyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MenuPane, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        BodyPaneLayout.setVerticalGroup(
            BodyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HeaderPane, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
                    .addComponent(BodyPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(HeaderPane, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BodyPane, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SetButtonActionPerformed

    private void CreateUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUserButtonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        System.out.println("Creating User...");
        Map UserMap = new HashMap();
        username = UserInput2.getText();
        password = PassInput2.getText();
        UserMap.put("username", username);
        UserMap.put("password", password);
        Object res = clothoObject.createUser(UserMap);
        System.out.println(username);
        System.out.println(password);
    }//GEN-LAST:event_CreateUserButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Logging In...");
        Map UserMap = new HashMap();
        username = UserInput1.getText();
        password = PassInput1.getText();
        UserMap.put("username", username);
        UserMap.put("password", password);
        Object res = clothoObject.login(UserMap);
        System.out.println(username);
        System.out.println(password);
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CreateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClothoJavaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClothoJavaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClothoJavaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClothoJavaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClothoJavaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPane;
    private javax.swing.JTextArea AboutText;
    private javax.swing.JPanel AccountPane;
    private javax.swing.JPanel BodyPane;
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton CreateHelp;
    private javax.swing.JPanel CreatePane;
    private javax.swing.JButton CreateUserButton;
    private javax.swing.JLabel CreateUserLabel;
    private javax.swing.JButton DestroyButton;
    private javax.swing.JButton DestroyHelp;
    private javax.swing.JPanel DestroyPane;
    private javax.swing.JPanel DownloadsPane;
    private javax.swing.JTabbedPane FunctionsList;
    private javax.swing.JPanel FunctionsPane;
    private javax.swing.JButton GetButton;
    private javax.swing.JButton GetHelp;
    private javax.swing.JPanel GetPane;
    private javax.swing.JLayeredPane HeaderPane;
    private javax.swing.JTextField IDInputDes;
    private javax.swing.JTextField IDInputGet;
    private javax.swing.JTextArea InsertJSONObj1;
    private javax.swing.JLabel JSONObjLabel;
    private javax.swing.JLabel JSONObjLabel1;
    private javax.swing.JLabel JSONObjLabel2;
    private javax.swing.JLabel JSONObjLabel3;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JTabbedPane MenuPane;
    private javax.swing.JLabel NonaIcon;
    private javax.swing.JLabel NyxIcon;
    private javax.swing.JTextArea NyxText;
    private javax.swing.JPasswordField PassInput1;
    private javax.swing.JPasswordField PassInput2;
    private javax.swing.JLabel PassLabel1;
    private javax.swing.JLabel PassLabel2;
    private javax.swing.JButton QueryButton;
    private javax.swing.JButton QueryHelp;
    private javax.swing.JPanel QueryPane;
    private javax.swing.JButton SetButton;
    private javax.swing.JTextArea SetEInput;
    private javax.swing.JLabel SetELabel;
    private javax.swing.JButton SetHelp;
    private javax.swing.JPanel SetPane;
    private javax.swing.JTextArea SetQInput;
    private javax.swing.JLabel SetQLabel;
    private javax.swing.JTextArea StartText;
    private javax.swing.JTextField UserInput1;
    private javax.swing.JTextField UserInput2;
    private javax.swing.JLabel UserLabel1;
    private javax.swing.JLabel UserLabel2;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
